//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetroleraManager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENDEDORES
    {
        public VENDEDORES()
        {
            this.COMPROBANTESVENTAS = new HashSet<COMPROBANTESVENTAS>();
        }
    
        public System.Guid ID { get; set; }
        public string Descripcion { get; set; }
        public string Email { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<COMPROBANTESVENTAS> COMPROBANTESVENTAS { get; set; }
    }
}
