//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetroleraManager.Web.Tramites.Informes {
    
    
    public partial class InformesObleasRealizadas {
        
        /// <summary>
        /// filtrosFechas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PetroleraManager.Web.UserControls.FiltrosFechas filtrosFechas;
        
        /// <summary>
        /// btnEnviar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PetroleraManager.Web.Controls.BtnAceptar btnEnviar;
        
        /// <summary>
        /// btnPdf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PetroleraManager.Web.Controls.BtnPdf btnPdf;
        
        /// <summary>
        /// btnExcel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PetroleraManager.Web.Controls.BtnExcel btnExcel;
        
        /// <summary>
        /// MessageBoxCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PetroleraManager.Web.UserControls.MessageBoxCtrl MessageBoxCtrl;
        
        /// <summary>
        /// PrintBoxCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PetroleraManager.Web.UserControls.PrintBoxCtrl PrintBoxCtrl;
    }
}
