//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetroleraManager.Web.Tramites.Informes {


    public partial class InformesLibroDiario {

        protected global::PetroleraManager.Web.UserControls.FiltrosFechas filtrosFechas;

        protected global::System.Web.UI.WebControls.TextBox txtCliente;

        protected global::System.Web.UI.WebControls.TextBox txtDominio;

        protected global::PetroleraManager.Web.Controls.BtnAceptar btnVer;

        protected global::PetroleraManager.Web.Controls.BtnPdf btnPdf;

        protected global::PetroleraManager.Web.UserControls.MessageBoxCtrl MessageBoxCtrl;

        protected global::System.Web.UI.HtmlControls.HtmlGenericControl fldResultados;

        protected global::PL.Fwk.Presentation.Web.Controls.PLGridView grdLibroDiario;

        protected global::PetroleraManager.Web.UserControls.PrintBoxCtrl PrintBoxCtrl;
    }
}
