//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalleresWeb.Web.MiCuenta {
    
    
    public partial class Usuario {
        
        /// <summary>
        /// tab control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTabContainer tab;
        
        /// <summary>
        /// pnlUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTabPanel pnlUsuario;
        
        /// <summary>
        /// hddUsuarioID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLHidden hddUsuarioID;
        
        /// <summary>
        /// txtUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtUsuario;
        
        /// <summary>
        /// txtNombreApellido control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtNombreApellido;
        
        /// <summary>
        /// cboTipoDoc control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TalleresWeb.Controls.CboTiposDocumentos cboTipoDoc;
        
        /// <summary>
        /// txtNroDocumento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtNroDocumento;
        
        /// <summary>
        /// txtEmail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtEmail;
        
        /// <summary>
        /// btnAceptarUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLButton btnAceptarUsuario;
        
        /// <summary>
        /// btnCancelarUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLButton btnCancelarUsuario;
        
        /// <summary>
        /// PLTabPanel1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTabPanel PLTabPanel1;
        
        /// <summary>
        /// txtPwActual control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtPwActual;
        
        /// <summary>
        /// txtPwNueva control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtPwNueva;
        
        /// <summary>
        /// txtPwConfirma control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtPwConfirma;
        
        /// <summary>
        /// btnCambiarContrasenia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLButton btnCambiarContrasenia;
        
        /// <summary>
        /// pnlTaller control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTabPanel pnlTaller;
        
        /// <summary>
        /// hddTallerID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLHidden hddTallerID;
        
        /// <summary>
        /// txtMatricula control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtMatricula;
        
        /// <summary>
        /// txtRazonSocial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtRazonSocial;
        
        /// <summary>
        /// txtDomicilio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtDomicilio;
        
        /// <summary>
        /// cboLocalidad control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TalleresWeb.Controls.CboLocalidades cboLocalidad;
        
        /// <summary>
        /// txtCuit control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBoxMasked txtCuit;
        
        /// <summary>
        /// txtTelefono control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtTelefono;
        
        /// <summary>
        /// txtFax control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtFax;
        
        /// <summary>
        /// txtEmailTaller control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtEmailTaller;
        
        /// <summary>
        /// txtContacto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtContacto;
        
        /// <summary>
        /// txtVenceContrato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBoxMasked txtVenceContrato;
        
        /// <summary>
        /// cboZona control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::TalleresWeb.Controls.CboZonas cboZona;
        
        /// <summary>
        /// txtHorarioAtencion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLTextBox txtHorarioAtencion;
        
        /// <summary>
        /// btnAceptarTaller control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLButton btnAceptarTaller;
        
        /// <summary>
        /// btnCancelarTaller control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::PL.Fwk.Presentation.Web.Controls.PLButton btnCancelarTaller;
        
        /// <summary>
        /// MessageBoxCtrl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Common.Web.UserControls.MessageBoxCtrl MessageBoxCtrl1;
    }
}
