//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DataModel", "FK_USUARIOS_ROLES", "ROLES", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PL.ServicesWeb.Entities.ROLES), "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PL.ServicesWeb.Entities.USUARIOS), true)]
[assembly: EdmRelationshipAttribute("DataModel", "FK_t_fwk_Services_t_fwk_Menu", "T_MENU", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(PL.ServicesWeb.Entities.T_MENU), "T_SERVICIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PL.ServicesWeb.Entities.T_SERVICIOS), true)]
[assembly: EdmRelationshipAttribute("DataModel", "T_ROLESSERVICIOS", "ROLES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PL.ServicesWeb.Entities.ROLES), "T_SERVICIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PL.ServicesWeb.Entities.T_SERVICIOS))]

#endregion

namespace PL.ServicesWeb.Entities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ServicesContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ServicesContext object using the connection string found in the 'ServicesContext' section of the application configuration file.
        /// </summary>
        public ServicesContext() : base("name=ServicesContext", "ServicesContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ServicesContext object.
        /// </summary>
        public ServicesContext(string connectionString) : base(connectionString, "ServicesContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ServicesContext object.
        /// </summary>
        public ServicesContext(EntityConnection connection) : base(connection, "ServicesContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ROLES> ROLES
        {
            get
            {
                if ((_ROLES == null))
                {
                    _ROLES = base.CreateObjectSet<ROLES>("ROLES");
                }
                return _ROLES;
            }
        }
        private ObjectSet<ROLES> _ROLES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_MENU> T_MENU
        {
            get
            {
                if ((_T_MENU == null))
                {
                    _T_MENU = base.CreateObjectSet<T_MENU>("T_MENU");
                }
                return _T_MENU;
            }
        }
        private ObjectSet<T_MENU> _T_MENU;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_SERVICIOS> T_SERVICIOS
        {
            get
            {
                if ((_T_SERVICIOS == null))
                {
                    _T_SERVICIOS = base.CreateObjectSet<T_SERVICIOS>("T_SERVICIOS");
                }
                return _T_SERVICIOS;
            }
        }
        private ObjectSet<T_SERVICIOS> _T_SERVICIOS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<USUARIOS> USUARIOS
        {
            get
            {
                if ((_USUARIOS == null))
                {
                    _USUARIOS = base.CreateObjectSet<USUARIOS>("USUARIOS");
                }
                return _USUARIOS;
            }
        }
        private ObjectSet<USUARIOS> _USUARIOS;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ROLES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToROLES(ROLES rOLES)
        {
            base.AddObject("ROLES", rOLES);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_MENU EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_MENU(T_MENU t_MENU)
        {
            base.AddObject("T_MENU", t_MENU);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_SERVICIOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_SERVICIOS(T_SERVICIOS t_SERVICIOS)
        {
            base.AddObject("T_SERVICIOS", t_SERVICIOS);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the USUARIOS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUSUARIOS(USUARIOS uSUARIOS)
        {
            base.AddObject("USUARIOS", uSUARIOS);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="ROLES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ROLES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ROLES object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        public static ROLES CreateROLES(global::System.Guid id, global::System.String descripcion)
        {
            ROLES rOLES = new ROLES();
            rOLES.ID = id;
            rOLES.Descripcion = descripcion;
            return rOLES;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.String _Activo;
        partial void OnActivoChanging(global::System.String value);
        partial void OnActivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_USUARIOS_ROLES", "USUARIOS")]
        public EntityCollection<USUARIOS> USUARIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<USUARIOS>("DataModel.FK_USUARIOS_ROLES", "USUARIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<USUARIOS>("DataModel.FK_USUARIOS_ROLES", "USUARIOS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "T_ROLESSERVICIOS", "T_SERVICIOS")]
        public EntityCollection<T_SERVICIOS> T_SERVICIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_SERVICIOS>("DataModel.T_ROLESSERVICIOS", "T_SERVICIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_SERVICIOS>("DataModel.T_ROLESSERVICIOS", "T_SERVICIOS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="T_MENU")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_MENU : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_MENU object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static T_MENU CreateT_MENU(global::System.Guid id)
        {
            T_MENU t_MENU = new T_MENU();
            t_MENU.ID = id;
            return t_MENU;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Activo;
        partial void OnActivoChanging(Nullable<global::System.Boolean> value);
        partial void OnActivoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_t_fwk_Services_t_fwk_Menu", "T_SERVICIOS")]
        public EntityCollection<T_SERVICIOS> T_SERVICIOS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_SERVICIOS>("DataModel.FK_t_fwk_Services_t_fwk_Menu", "T_SERVICIOS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_SERVICIOS>("DataModel.FK_t_fwk_Services_t_fwk_Menu", "T_SERVICIOS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="T_SERVICIOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_SERVICIOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_SERVICIOS object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static T_SERVICIOS CreateT_SERVICIOS(global::System.Guid id)
        {
            T_SERVICIOS t_SERVICIOS = new T_SERVICIOS();
            t_SERVICIOS.ID = id;
            return t_SERVICIOS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> MenuID
        {
            get
            {
                return _MenuID;
            }
            set
            {
                OnMenuIDChanging(value);
                ReportPropertyChanging("MenuID");
                _MenuID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MenuID");
                OnMenuIDChanged();
            }
        }
        private Nullable<global::System.Guid> _MenuID;
        partial void OnMenuIDChanging(Nullable<global::System.Guid> value);
        partial void OnMenuIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private Nullable<global::System.Boolean> _Activo;
        partial void OnActivoChanging(Nullable<global::System.Boolean> value);
        partial void OnActivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_t_fwk_Services_t_fwk_Menu", "T_MENU")]
        public T_MENU T_MENU
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MENU>("DataModel.FK_t_fwk_Services_t_fwk_Menu", "T_MENU").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MENU>("DataModel.FK_t_fwk_Services_t_fwk_Menu", "T_MENU").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_MENU> T_MENUReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_MENU>("DataModel.FK_t_fwk_Services_t_fwk_Menu", "T_MENU");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_MENU>("DataModel.FK_t_fwk_Services_t_fwk_Menu", "T_MENU", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "T_ROLESSERVICIOS", "ROLES")]
        public EntityCollection<ROLES> ROLES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ROLES>("DataModel.T_ROLESSERVICIOS", "ROLES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ROLES>("DataModel.T_ROLESSERVICIOS", "ROLES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DataModel", Name="USUARIOS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class USUARIOS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new USUARIOS object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="descripcion">Initial value of the Descripcion property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="rolID">Initial value of the RolID property.</param>
        /// <param name="activo">Initial value of the Activo property.</param>
        public static USUARIOS CreateUSUARIOS(global::System.Guid id, global::System.String descripcion, global::System.String password, global::System.Guid rolID, global::System.Boolean activo)
        {
            USUARIOS uSUARIOS = new USUARIOS();
            uSUARIOS.ID = id;
            uSUARIOS.Descripcion = descripcion;
            uSUARIOS.Password = password;
            uSUARIOS.RolID = rolID;
            uSUARIOS.Activo = activo;
            return uSUARIOS;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Guid _ID;
        partial void OnIDChanging(global::System.Guid value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Descripcion
        {
            get
            {
                return _Descripcion;
            }
            set
            {
                OnDescripcionChanging(value);
                ReportPropertyChanging("Descripcion");
                _Descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Descripcion");
                OnDescripcionChanged();
            }
        }
        private global::System.String _Descripcion;
        partial void OnDescripcionChanging(global::System.String value);
        partial void OnDescripcionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreYApellido
        {
            get
            {
                return _NombreYApellido;
            }
            set
            {
                OnNombreYApellidoChanging(value);
                ReportPropertyChanging("NombreYApellido");
                _NombreYApellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreYApellido");
                OnNombreYApellidoChanged();
            }
        }
        private global::System.String _NombreYApellido;
        partial void OnNombreYApellidoChanging(global::System.String value);
        partial void OnNombreYApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> TipoDocID
        {
            get
            {
                return _TipoDocID;
            }
            set
            {
                OnTipoDocIDChanging(value);
                ReportPropertyChanging("TipoDocID");
                _TipoDocID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TipoDocID");
                OnTipoDocIDChanged();
            }
        }
        private Nullable<global::System.Guid> _TipoDocID;
        partial void OnTipoDocIDChanging(Nullable<global::System.Guid> value);
        partial void OnTipoDocIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NroDocumento
        {
            get
            {
                return _NroDocumento;
            }
            set
            {
                OnNroDocumentoChanging(value);
                ReportPropertyChanging("NroDocumento");
                _NroDocumento = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NroDocumento");
                OnNroDocumentoChanged();
            }
        }
        private global::System.String _NroDocumento;
        partial void OnNroDocumentoChanging(global::System.String value);
        partial void OnNroDocumentoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid RolID
        {
            get
            {
                return _RolID;
            }
            set
            {
                OnRolIDChanging(value);
                ReportPropertyChanging("RolID");
                _RolID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RolID");
                OnRolIDChanged();
            }
        }
        private global::System.Guid _RolID;
        partial void OnRolIDChanging(global::System.Guid value);
        partial void OnRolIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.Boolean _Activo;
        partial void OnActivoChanging(global::System.Boolean value);
        partial void OnActivoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DataModel", "FK_USUARIOS_ROLES", "ROLES")]
        public ROLES ROLES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ROLES>("DataModel.FK_USUARIOS_ROLES", "ROLES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ROLES>("DataModel.FK_USUARIOS_ROLES", "ROLES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ROLES> ROLESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ROLES>("DataModel.FK_USUARIOS_ROLES", "ROLES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ROLES>("DataModel.FK_USUARIOS_ROLES", "ROLES", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
